config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/rcauth-eu/aarc-delegation-server:
      branch: 0.2.4-release
      repo: https://github.com/rcauth-eu/aarc-delegation-server.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/rcauth-eu/aarc-delegation-server git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-puce-capuchin.sh
        container: qc.acc_queasy-lemon-walrus
  QC.Doc:
    repos:
      github.com/rcauth-eu/aarc-delegation-server find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-bistre-gharial.sh
        container: qc.doc_crappy-brass-forest
      github.com/rcauth-eu/aarc-delegation-server git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-turquoise-dunker.sh
        container: qc.doc_pokey-sangria-coati
      github.com/rcauth-eu/aarc-delegation-server markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-grey-pinscher.sh
        container: qc.doc_grumpy-apricot-turtle
  QC.Lic:
    repos:
      github.com/rcauth-eu/aarc-delegation-server licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-magnolia-baboon.sh
        container: qc.lic_breezy-chestnut-squirt
  QC.Sty:
    repos:
      github.com/rcauth-eu/aarc-delegation-server checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-wisteria-hyena.sh
        container: qc.sty_surly-copper-hedgehog
  QC.Ver:
    repos:
      github.com/rcauth-eu/aarc-delegation-server get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-carmine-tiger.sh
        container: qc.ver_scanty-brown-hummingbird
timeout: 5400
